//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateur
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Email { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string Province { get; set; }
        public string CP { get; set; }
        public string MotDePasse { get; set; }
        public string Genre { get; set; }
        public Nullable<bool> choice { get; set; }
        public int Criteres_Id { get; set; }
    
        public virtual Criteres Criteres { get; set; }
    }
}
